- name: Remove apache
  hosts: myhosts
  tasks:
   - name: Remove apache
     ansible.builtin.apt:
      name: apache2
      state: absent

   - name: Remove apache service
     ansible.builtin.service:
      name: apache2
      state: stopped