- name: My first play
  hosts: myhosts
  tasks:
    - name: Install apache2 and systemctl
      ansible.builtin.apt:
        name:
        - apache2
        - systemctl
        state: present
        update_cache: yes

    - name: Start apache service
      ansible.builtin.service:
        name: apache2
        state: started

