- name: Remove apache
  hosts: myhosts
  tasks:
   - name: Stop apache service
     ansible.builtin.service:
      name: apache2
      state: stopped
      
   - name: Remove apache
     ansible.builtin.apt:
      name: apache2
      state: absent
